tasks:
  - init: cargo install cargo-watch && cargo build
    command: cargo build

vscode:
  extensions:
    - k--kato.intellij-idea-keybindings
    - GitHub.copilot-nightly
    - rust-lang.rust-analyzer
    - vadimcn.vscode-lldb
    - ms-azuretools.vscode-docker